### ISSUE TITLE
Error with shapes of the inverse_transform method

### ISSUE THREAD

**Issue by donand** [Andres-Hernandez/CalibrationNN#1]
Hi,

When running the preparation of the training data with versions of scikit-learn greater or equal than 0.19 it gives an error, because the `inverse_transform` method of the `pipeline` object in the `instruments.py` file returns a one-dimensional array instead of a two-dimensional one when the input is one-dimensional.

**Comment by Andres-Hernandez** [comment]
Indeed, the warning message about the automatic broadcasting being deprecated in later versions had appeared already in earlier versions, but I had not looked at it. 

I am traveling now, but I will update scikit-learn next week and and fix it.

**Comment by Andres-Hernandez** [comment]
Sorry for the big delay, but things got in the way. I have corrected the bug
